EMBEDDING LAYER ADDITION PRACTICAL

In [1]:
from tensorflow.keras.preprocessing.text import  one_hot

In [2]:
#Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
#Define the vocabulary size
voc_size = 10000

In [4]:
#One hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2139, 1944, 4207, 1967],
 [2139, 1944, 4207, 1101],
 [2139, 3651, 4207, 3137],
 [6569, 4815, 8075, 7576, 8899],
 [6569, 4815, 8075, 7576, 8101],
 [2527, 2139, 4585, 4207, 2859],
 [9452, 6533, 1610, 7576]]

In [5]:
#Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8                 #to make every sentence input vector of equal size
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 2139 1944 4207 1967]
 [   0    0    0    0 2139 1944 4207 1101]
 [   0    0    0    0 2139 3651 4207 3137]
 [   0    0    0 6569 4815 8075 7576 8899]
 [   0    0    0 6569 4815 8075 7576 8101]
 [   0    0    0 2527 2139 4585 4207 2859]
 [   0    0    0    0 9452 6533 1610 7576]]


In [7]:
#feature representation
dim=10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Lenovo\Desktop\Data Science\RNN_Project\envt\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)                #embedding layer converting the input sentences into vectors

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step


array([[[ 0.04038445,  0.00978289,  0.0398729 ,  0.01530294,
          0.03933731, -0.04332018,  0.01895234,  0.04653491,
          0.03107244,  0.0430159 ],
        [ 0.04038445,  0.00978289,  0.0398729 ,  0.01530294,
          0.03933731, -0.04332018,  0.01895234,  0.04653491,
          0.03107244,  0.0430159 ],
        [ 0.04038445,  0.00978289,  0.0398729 ,  0.01530294,
          0.03933731, -0.04332018,  0.01895234,  0.04653491,
          0.03107244,  0.0430159 ],
        [ 0.04038445,  0.00978289,  0.0398729 ,  0.01530294,
          0.03933731, -0.04332018,  0.01895234,  0.04653491,
          0.03107244,  0.0430159 ],
        [-0.03470842, -0.03580547, -0.00713571,  0.00878253,
         -0.04399235,  0.04959252, -0.03496295,  0.00664157,
          0.01661477, -0.02469329],
        [-0.0471239 ,  0.0475958 ,  0.03849034, -0.00556457,
          0.02592683, -0.04365028,  0.03102623, -0.04028908,
          0.03384635,  0.00888563],
        [ 0.01069059, -0.0169313 , -0.01137873,  0.0